/* DO NOT EDIT THIS FILE.  
   It is generated by the program features.sch in the Larceny root directory.
   */
#ifndef INCLUDED_CONFIG_H
#define INCLUDED_CONFIG_H
#undef SPARC
#undef X86_SASSY
#undef X86_NASM
#undef ARM
#undef PPC_GAS
#undef PETIT_LARCENY
#undef BITS_32
#undef BITS_64
#undef ENDIAN_LITTLE
#undef BIG_ENDIAN
#undef EXPLICIT_DIVZ_CHECK
#undef FLUSH_ALWAYS
#undef FLUSH_NEVER
#undef HARDWARE_DIVISION
#undef SPARCV9
#undef PENTIUM
#undef SUNOS4
#undef SUNOS5
#undef LINUX
#undef MACOS_X
#undef BSD_UNIX
#undef POSIX_UNIX
#undef XOPEN_UNIX
#undef CYGWIN
#undef WIN32
#undef MACOS
#undef GENERIC_OS
#undef SUNOS
#undef UNIX
#undef BSD_SIGNALS
#undef STDC_SIGNALS
#undef POSIX_SIGNALS
#undef XOPEN_SIGNALS
#undef WIN32_SIGNALS
#undef ROF_COLLECTOR
#undef STACK_UNDERFLOW_COUNTING
#undef GCLIB_LARGE_TABLE
#undef RETURN_MEMORY_TO_OS
#undef GC_HIRES_TIMERS
#undef GC_EVENT_COUNTERS
#undef USE_GENERIC_ALLOCATOR
#undef USE_GENERIC_IO
#undef USE_GENERIC_FILESYSTEM
#undef USE_STDIO
#undef USE_LONGJUMP
#undef USE_RETURN_WITHOUT_VALUE
#undef USE_RETURN_WITH_VALUE
#undef USE_GOTOS_LOCALLY
#undef USE_CACHED_STATE
#undef DYNAMIC_LOADING
#undef CODEPTR_SHIFT1
#undef CODEPTR_SHIFT2
#undef CODEWARRIOR
#undef DEC_ALPHA_32BIT
#undef NO_ATOMIC_ALLOCATION
#undef NO_SYNCHRONOUS_SIGNALS
#undef DEBIAN_STRDUP_WEIRDNESS
#undef SIMULATE_NEW_BARRIER
#undef HAVE_RINT
#undef HAVE_AINT
#undef HAVE_STRNCASECMP
#undef HAVE_STRDUP
#undef HAVE_HRTIME_T
#undef HAVE_STAT
#undef HAVE_POLL
#undef HAVE_SELECT
#undef HAVE_DLFCN
#define POSIX_SIGNALS 1
#define UNIX 1
#define ROF_COLLECTOR 1
#define PETIT_LARCENY 1
#define BITS_32 1
#define ENDIAN_LITTLE 1
#define LINUX 1
#define HAVE_RINT 1
#define HAVE_STRNCASECMP 1
#define HAVE_STRDUP 1
#define HAVE_POLL 1
#define HAVE_DLFCN 1
#define DYNAMIC_LOADING 1
#define STACK_UNDERFLOW_COUNTING 1
#define DEBIAN_STRDUP_WEIRDNESS 1
#define USE_CACHED_STATE 1
#ifndef DATE
#  ifdef __DATE__
#    define DATE __DATE__
#  else
#    define DATE "Jan 29 1964"
# endif
#endif
#ifndef TIME
#  ifdef __TIME__
#    define TIME __TIME__
#  else
#    define TIME "03:00:00"
#  endif
#endif
#ifndef USER
#  ifdef __USER__
#    define USER __USER__
#  else
#    define USER "stanley"
#  endif
#endif
#endif /* INCLUDED_CONFIG_H */
